const net = require('net');

const STX = 0x02;
const ETX = 0x03;
const ACK = 0x06;
const NAK = 0x15;

class RaiffeisenEcrService {
  constructor(ip, port = 1000) {
    this.ip = ip;
    this.port = port;
  }

  /**
   * Calculates Longitudinal Redundancy Check (LRC)
   * LRC is generated by Exclusive-OR'ing all data bytes following STX, up to and including ETX.
   */
  calculateLRC(buffer) {
    let lrc = 0;
    // Buffer structure expected: [STX, ...data..., ETX, LRC(placeholder)]
    for (let i = 1; i < buffer.length - 1; i++) {
        lrc ^= buffer[i];
    }
    return lrc;
  }

  /**
   * Constructs the message frame: STX | MesssageID + MessageType + . + Payload | ETX | LRC
   */
  buildMessage(messageId, messageType, payload) {
    const msg = messageId + messageType + '.' + payload;
    const msgBuffer = Buffer.from(msg, 'ascii');
    
    // Total size: STX(1) + Msg length + ETX(1) + LRC(1 byte)
    const outBuf = Buffer.alloc(msgBuffer.length + 3);
    
    outBuf[0] = STX;
    msgBuffer.copy(outBuf, 1);
    outBuf[outBuf.length - 2] = ETX;
    
    // Calculate and set LRC on the last byte
    outBuf[outBuf.length - 1] = this.calculateLRC(outBuf);
    return outBuf;
  }

  /**
   * Initiates payment flow and handles standard Hypercom MOL T7 ECR Protocol
   * 1. Send 10 (MOL10.)
   * 2. Wait ACK
   * 3. Wait 11 (MOL11.), Send ACK
   * 4. Wait 12 (MOL12.), Send ACK
   * 5. Send 13 (MOL13.), Wait ACK
   */
  async processPayment(amount) {
    if (!amount || amount <= 0) throw new Error('Invalid payment amount');
    
    // Format amount: 12 digits, right justified with zero padding, no decimal point (implied by currency)
    // E.g. 25.50 -> 2550 -> 000000002550
    const amountInCents = Math.round(amount * 100);
    const amountStr = String(amountInCents).padStart(12, '0'); 
    
    const reqCmd = this.buildMessage('MOL', '10', amountStr);

    return new Promise((resolve, reject) => {
      const client = new net.Socket();
      client.setTimeout(75000); // Transaction takes max ~60s
      
      let state = 'WAITING_ACK_10';
      let fullBuffer = Buffer.alloc(0);
      let transactionFinished = false;

      client.connect(this.port, this.ip, () => {
        console.log(`[Raiffeisen POS] Connected to ${this.ip}:${this.port}. Initiating transaction...`);
        client.write(reqCmd);
      });

      client.on('data', (data) => {
        fullBuffer = Buffer.concat([fullBuffer, data]);

        // Process bytes from the buffer
        let offset = 0;
        while (offset < fullBuffer.length) {
            const byte = fullBuffer[offset];

            if (byte === ACK) {
                if (state === 'WAITING_ACK_10') {
                    console.log(`[Raiffeisen POS] Received ACK for 10. Awaiting response 11...`);
                    state = 'WAITING_11';
                }
                offset++;
            } 
            else if (byte === NAK) {
                console.error(`[Raiffeisen POS] Received NAK from terminal!`);
                client.destroy();
                if (!transactionFinished) reject(new Error('POS returned NAK - Message Denied or Bad LRC'));
                return;
            } 
            else if (byte === STX) {
                // Find matching ETX
                const etxIndex = fullBuffer.indexOf(ETX, offset);
                if (etxIndex !== -1 && fullBuffer.length > etxIndex + 1) {
                    // Frame Complete: STX -> ETX -> LRC
                    const msgFrame = fullBuffer.subarray(offset, etxIndex + 2); 
                    const payload = msgFrame.subarray(1, -2).toString('ascii'); // Extract pure payload
                    
                    if (payload.startsWith('MOL11.')) {
                        console.log(`[Raiffeisen POS] Received MOL11 (Initiate success). Terminal waiting for User Card...`);
                        state = 'WAITING_12';
                        client.write(Buffer.from([ACK])); // Acknowledge the 11 message
                    } 
                    else if (payload.startsWith('MOL12.')) {
                        console.log(`[Raiffeisen POS] Received MOL12 (Authorization Response).`);
                        
                        // Parse MOL12 Payload
                        // MOL12.XX..... 
                        // Response code is 2 chars right after MOL12. => positions 6-7 (0-indexed)
                        const responseCode = payload.slice(6, 8);
                        
                        // Wait briefly before sending ACK for MOL12 to ensure stability
                        client.write(Buffer.from([ACK]));
                        
                        // Terminal expects MOL13 (Authorization Acknowledgment) to finish
                        const ackCmd = this.buildMessage('MOL', '13', '');
                        client.write(ackCmd);
                        
                        transactionFinished = true;
                        setTimeout(() => client.destroy(), 500); // Disconnect after cleanup
                        
                        if (responseCode === '00') {
                            resolve({ success: true, code: responseCode, raw: payload });
                        } else {
                            resolve({ success: false, reason: 'Transaction denied by Issuer/Bank', code: responseCode, raw: payload });
                        }
                    }
                    
                    offset = etxIndex + 2; // Jump over this packet
                } else {
                    // Frame incomplete, wait for more data
                    break;
                }
            } else {
                // Unknown garbage byte
                offset++;
            }
        }
        
        // Remove processed bytes from buffer
        if (offset > 0) {
            fullBuffer = fullBuffer.subarray(offset);
        }
      });

      client.on('error', (err) => {
        console.error(`[Raiffeisen POS] Socket Error:`, err.message);
        if (!transactionFinished) reject(err);
      });

      client.on('timeout', () => {
        console.error(`[Raiffeisen POS] Timeout! Transaction aborted.`);
        client.destroy();
        if (!transactionFinished) reject(new Error('Connection timeout waiting for POS operation'));
      });
      
      client.on('close', () => {
        if (!transactionFinished) reject(new Error('Connection abruptly closed by POS'));
      });
    });
  }
}

module.exports = RaiffeisenEcrService;
