[build]
  command = "npm run build"
  publish = "dist"

  [build.environment]
    VITE_BACKEND_URL = "https://smart-kiosk-v7ws.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
